### PR TITLE
Fix empty comments. Remove unused code.

### PR DESCRIPTION
**Pull request by alipang**
The schema file don't work with php-7.2.

### CODE REVIEW

**Comment by inreti-sb** [comment]
Thanks @alipang for your work! Can someone merge this and publish a new version of Quip?

**Comment by alipang** [comment]
Yes! It's good to see some action on this extra. I think I have more to come, but these are my first github and phpstorm experiences.

**Comment by rthrash** [comment]
This pull request has been mentioned on **Community**. There might be relevant details there:

https://community.modx.com/t/quip-not-showing-comments-properly/809/5

**Comment by rthrash** [comment]
This pull request has been mentioned on **Community**. There might be relevant details there:

https://community.modx.com/t/quip-reply-to-thread-showing-unapproved-for-parent-comments/838/2

**Comment by rthrash** [comment]
This pull request has been mentioned on **Community**. There might be relevant details there:

https://community.modx.com/t/quip-reply-to-thread-showing-unapproved-for-parent-comments/838/3

**Comment by Mark-H** [comment]
This has come up a few times now, fixing the issue each time, so would be great to get released. @JoshuaLuckers does your adoption of Articles also include Quip? :P

**Comment by JoshuaLuckers** [comment]
@Mark-H Yeah, why not! I can give it some attention now and then :). 

@rthrash it would be great if I could maintain this repo (like Articles)!

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/article-comment-message-coming-through-as-0/2232/5

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/article-comment-message-coming-through-as-0/2232/7

**Comment by rthrash** [comment]
This pull request has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/all-replay-texts-in-articles-turn-to-0/3036/3

**Pull request merged**
